//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCIWallet
{
    using System;
    using System.Collections.Generic;
    
    public partial class tStgPayment
    {
        public decimal IID { get; set; }
        public string AccountID { get; set; }
        public string TransactionNumber { get; set; }
        public string TokenID { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
    }
}
