//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCIWallet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class dbPCITokenEntities1 : DbContext
    {
        public dbPCITokenEntities1()
            : base("name=dbPCITokenEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tPaymentTransaction> tPaymentTransactions { get; set; }
        public DbSet<tPCIToken> tPCITokens { get; set; }
        public DbSet<tStgPayment> tStgPayments { get; set; }
    
        public virtual ObjectResult<uspGetWallet_Result> uspGetWallet(string pAccountId)
        {
            var pAccountIdParameter = pAccountId != null ?
                new ObjectParameter("pAccountId", pAccountId) :
                new ObjectParameter("pAccountId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspGetWallet_Result>("uspGetWallet", pAccountIdParameter);
        }
    }
}
