//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentsPCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPaymentTransaction
    {
        public decimal IID { get; set; }
        public string AccountID { get; set; }
        public string TransactionNumber { get; set; }
        public string TokenID { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public decimal PaymentAmount { get; set; }
        public string TransactionType { get; set; }
        public string TransactionStatus { get; set; }
    }
}
