//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentsPCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPCIToken
    {
        public decimal IID { get; set; }
        public string TokenID { get; set; }
        public string CreditCardNumber { get; set; }
        public string BankAccountNumber { get; set; }
        public string RoutingNumber { get; set; }
    }
}
