//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentsPCI.CustWalletSVC {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WalletInfo", Namespace="http://schemas.datacontract.org/2004/07/PCIWallet")]
    [System.SerializableAttribute()]
    public partial class WalletInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentAccountLastFourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoutingNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToketIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountID {
            get {
                return this.AccountIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountIDField, value) != true)) {
                    this.AccountIDField = value;
                    this.RaisePropertyChanged("AccountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentAccountLastFour {
            get {
                return this.PaymentAccountLastFourField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentAccountLastFourField, value) != true)) {
                    this.PaymentAccountLastFourField = value;
                    this.RaisePropertyChanged("PaymentAccountLastFour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoutingNumber {
            get {
                return this.RoutingNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RoutingNumberField, value) != true)) {
                    this.RoutingNumberField = value;
                    this.RaisePropertyChanged("RoutingNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToketID {
            get {
                return this.ToketIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ToketIDField, value) != true)) {
                    this.ToketIDField = value;
                    this.RaisePropertyChanged("ToketID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustWalletSVC.ICustomerWallet")]
    public interface ICustomerWallet {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerWallet/RetrieveWallet", ReplyAction="http://tempuri.org/ICustomerWallet/RetrieveWalletResponse")]
        PaymentsPCI.CustWalletSVC.WalletInfo[] RetrieveWallet(string AccountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerWallet/RetrieveWallet", ReplyAction="http://tempuri.org/ICustomerWallet/RetrieveWalletResponse")]
        System.Threading.Tasks.Task<PaymentsPCI.CustWalletSVC.WalletInfo[]> RetrieveWalletAsync(string AccountId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerWalletChannel : PaymentsPCI.CustWalletSVC.ICustomerWallet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerWalletClient : System.ServiceModel.ClientBase<PaymentsPCI.CustWalletSVC.ICustomerWallet>, PaymentsPCI.CustWalletSVC.ICustomerWallet {
        
        public CustomerWalletClient() {
        }
        
        public CustomerWalletClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerWalletClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerWalletClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerWalletClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PaymentsPCI.CustWalletSVC.WalletInfo[] RetrieveWallet(string AccountId) {
            return base.Channel.RetrieveWallet(AccountId);
        }
        
        public System.Threading.Tasks.Task<PaymentsPCI.CustWalletSVC.WalletInfo[]> RetrieveWalletAsync(string AccountId) {
            return base.Channel.RetrieveWalletAsync(AccountId);
        }
    }
}
